const express = require('express');
const router = express.Router();
const authMiddleware = require('../middleware/auth');
const { allowRoles } = require('../middleware/authorize');
const User = require('../models/User');
const TeacherSalaryProfile = require('../models/TeacherSalaryProfile');
const TeacherAttendance = require('../models/TeacherAttendance');
const PayrollRun = require('../models/PayrollRun');
const { logAudit } = require('../utils/audit');
const {
    normalizeMonthKey,
    getTeacherAttendanceForPayroll,
    buildPayrollRun,
    persistPayrollRun,
} = require('../services/payrollCalculation');

function actorId(req) {
    return req.user?.userId || req.user?.id;
}

router.use(authMiddleware);
router.use(allowRoles('accountant', 'admin', 'super-admin'));

router.get('/teachers', async (req, res) => {
    try {
        const teachers = await User.find({ role: 'teacher' }).select('_id name email');
        return res.json({ success: true, teachers });
    } catch (error) {
        return res.status(500).json({ success: false, error: 'Failed to load teachers' });
    }
});

router.get('/preview', async (req, res) => {
    try {
        const { teacherId, monthKey } = req.query;
        if (!teacherId || !monthKey) {
            return res.status(400).json({ success: false, error: 'teacherId and monthKey required' });
        }
        const built = await buildPayrollRun(teacherId, monthKey, actorId(req));
        return res.json({
            success: true,
            preview: {
                ...built.amounts,
                attendanceSource: built.attendance.source,
                monthKey: built.monthKey,
            },
        });
    } catch (error) {
        return res.status(error.status || 500).json({
            success: false,
            error: error.message || 'Failed to preview payroll',
        });
    }
});

router.post('/salary-profile', async (req, res) => {
    try {
        const { teacherId, monthlySalary, workingDays, currency } = req.body;
        const profile = await TeacherSalaryProfile.findOneAndUpdate(
            { teacher: teacherId },
            { monthlySalary, workingDays, currency: currency || 'USD' },
            { upsert: true, new: true }
        );
        await logAudit({
            actor: actorId(req),
            action: 'payroll.salaryProfile.save',
            targetType: 'User',
            targetId: teacherId,
            details: { monthlySalary, workingDays },
        });
        return res.json({ success: true, profile });
    } catch (error) {
        return res.status(500).json({ success: false, error: 'Failed to save salary profile' });
    }
});

router.post('/attendance', async (req, res) => {
    try {
        const { teacherId, monthKey, presentDays, leaveDays, absentDays, notes } = req.body;
        const key = normalizeMonthKey(monthKey);
        const attendance = await TeacherAttendance.findOneAndUpdate(
            { teacher: teacherId, monthKey: key },
            {
                presentDays,
                leaveDays,
                absentDays: absentDays ?? 0,
                notes: notes || '',
            },
            { upsert: true, new: true }
        );
        await logAudit({
            actor: actorId(req),
            action: 'payroll.attendance.save',
            targetType: 'User',
            targetId: teacherId,
            details: { monthKey: key, presentDays, leaveDays, absentDays: absentDays ?? 0 },
        });
        return res.json({ success: true, attendance });
    } catch (error) {
        return res.status(500).json({ success: false, error: 'Failed to save teacher attendance' });
    }
});

router.post('/run', async (req, res) => {
    try {
        const { teacherId, monthKey } = req.body;
        const result = await persistPayrollRun(teacherId, monthKey, actorId(req), {
            autoGenerated: false,
            status: 'pending_review',
        });

        await logAudit({
            actor: actorId(req),
            action: 'payroll.run',
            targetType: 'User',
            targetId: teacherId,
            details: {
                monthKey: result.payroll.monthKey,
                finalSalary: result.calculation.finalSalary,
                deduction: result.calculation.deduction,
                attendanceSource: result.calculation.attendanceSource,
            },
        });

        return res.json({
            success: true,
            payroll: result.payroll,
            calculation: result.calculation,
        });
    } catch (error) {
        return res.status(error.status || 500).json({
            success: false,
            error: error.message || 'Failed to generate payroll',
        });
    }
});

router.get('/runs', async (req, res) => {
    try {
        const runs = await PayrollRun.find()
            .populate('teacher', 'name email')
            .populate('generatedBy', 'name')
            .sort({ createdAt: -1 })
            .limit(200);
        return res.json({ success: true, runs });
    } catch (error) {
        return res.status(500).json({ success: false, error: 'Failed to load payroll runs' });
    }
});

module.exports = router;
