const mongoose = require('mongoose');

const payrollRunSchema = new mongoose.Schema(
    {
        teacher: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
        teacherName: { type: String, default: '' },
        teacherEmail: { type: String, default: '' },
        monthKey: { type: String, required: true },
        monthlySalary: { type: Number, required: true },
        workingDays: { type: Number, required: true },
        presentDays: { type: Number, default: 0 },
        lateDays: { type: Number, default: 0 },
        leaveDays: { type: Number, default: 0 },
        absentDays: { type: Number, default: 0 },
        deductionDays: { type: Number, default: 0 },
        deduction: { type: Number, default: 0 },
        finalSalary: { type: Number, required: true },
        attendanceSource: { type: String, default: 'approved_request' },
        status: {
            type: String,
            enum: ['pending_review', 'paid', 'stale', 'rejected'],
            default: 'pending_review',
        },
        autoGenerated: { type: Boolean, default: false },
        staleReason: { type: String, default: null },
        generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
        paidAt: { type: Date, default: null },
        paidBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
        rejectedAt: { type: Date, default: null },
        rejectedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
        accountantNotes: { type: String, default: '' },
        editedByAccountant: { type: Boolean, default: false },
    },
    { timestamps: true }
);

payrollRunSchema.index({ teacher: 1, monthKey: 1 }, { unique: true });
payrollRunSchema.index({ status: 1, monthKey: -1 });

module.exports = mongoose.model('PayrollRun', payrollRunSchema);
